version: "3.9"
services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./.pgdata:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    env_file: 
      - local.env

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      # - DATABASE_URL=postgres://<useer>:<password>@<host>:<port>/<dbname>?<param1=value1&...>
    depends_on:
      - postgres