# Learn more: https://docs.docker.com/compose/reference/
#
# Build images:   docker-compose build
# Start app:      docker-compose up borda
# Start database: docker-compose up db
# Import tasks:   docker-compose up import-tasks
# Stop all:       docker-compose down (add -v to wipe db)
#
version: "3.9"
services:
  borda:
    image: borda-api-server
    container_name: borda-api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  import-tasks:
    image: borda-api-server:latest
    build:
      context: .
    environment:
      - .env
    depends_on:
      - db
    command: ["import-tasks", 
      "--token", "${GITHUB_ACCESS_TOKEN}",
      "--repo", "${TASK_REPOSITORY_URL}",
      "--db", "${DATABASE_URL}"]

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      # Permission denied when creating db
      # https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
      - ./.postgres/data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - db

#networks:
#  backend:
#
#volumes:
#  db-data: