DROP TABLE IF EXISTS task_submissions;
DROP TABLE IF EXISTS solved_tasks;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;