DROP TABLE IF EXISTS task_submissions;
DROP TABLE IF EXISTS solved_tasks;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user;