DROP TABLE IF EXISTS task_submission;
DROP TABLE IF EXISTS solved_task;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS team_member;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user;